export const basePayload = {
  "form-id": "52",
  "lead-id": null,
  "field-ids": ["14", "40", "69"],
  "gravityview-meta": false,
  "field-values": {
    "8": "",
    "9": ["", "", "am"],
    "11": ["", "", "am"],
    "14": "",
    "22": "",
    "38": "",
    "39": "",
    "40": "",
    "43": "0",
    "49": "",
    "55": "48",
    "56": "",
    "63": "Samuel Mwangi",
    "65": "",
    "67": "Board",
    "68": "iGaming Afrika",
    "69": "Sand",
    "71": "",
    "72": "",
  },
  "merge-tags": ["@{Hours:43}", "@{Cluster:69}", "@{Account Manager:40}"],
  "lmt-nonces": {
    "{Hours:43}": "aa1e1e4c2b",
    "{Cluster:69}": "c672e2ec74",
    "{Account Manager:40}": "4ace45977c",
  },
  "current-merge-tag-values": {
    "@{Hours:43}": "",
    "@{Cluster:69}": "Water",
    "@{Account Manager:40}": "",
  },
  security: "8be24b9c42",
  show_admin_fields_in_ajax: "",
};
